version: '3.8'
services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: online_edu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis-broker:
    image: redis:alpine

  django-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres-db
      DB_NAME: online_edu
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis-broker:6379/0
    depends_on:
      - postgres-db
      - redis-broker

  celery-worker:
    build: .
    command: celery -A core worker -l info
    environment:
      DB_HOST: postgres-db
      DB_NAME: online_edu
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis-broker:6379/0
    depends_on:
      - postgres-db
      - redis-broker
      - django-backend

  celery-beat:
    build: .
    command: celery -A core beat -l info
    environment:
      DB_HOST: postgres-db
      DB_NAME: online_edu
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis-broker:6379/0
    depends_on:
      - postgres-db
      - redis-broker
      - django-backend